---
- name: Tap!
  homebrew_tap:
    tap: "{{ item }}"
  with_items:
    - caskroom/cask
    - caskroom/versions
    - greymd/tools

- name: Install packages
  homebrew:
    name : "{{ item }}"
    state: latest
  with_items:
    - colordiff
    - direnv
    - fish
    - hub
    - jq
    - nkf
    - mycli
    - reattach-to-user-namespace
    - rbenv
    - ruby-build
    - tig
    - tmux
    - tmux-xpanes
    - tree
    - unar
    - wireshark

- name: Install packages with cask
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - atom
    - docker
    - dropbox
    - java8
    - google-chrome
    - google-japanese-ime
    - iterm2
    - jetbrains-toolbox
    - vagrant
    - virtualbox
    - wireshark
