---
- name: Start and Enable docker
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Append the docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
  become: true
